import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

type Manifest={chunks:Array<{rootName:string}>;guides:Array<{type:string;points:number[][]}>};
const canvas=document.querySelector<HTMLCanvasElement>('#view')!; const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x26312e);scene.add(new THREE.HemisphereLight(0xffffff,0x25362e,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(30,50,20);scene.add(sun);scene.add(new THREE.GridHelper(200,200,0x789085,0x46564f));
const camera=new THREE.PerspectiveCamera(45,1,.1,1000);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;const content=new THREE.Group();scene.add(content);const overlays=new THREE.Group();scene.add(overlays);
const status=document.querySelector('#status')!;const chunks=document.querySelector('#chunks')!;const stats=document.querySelector('#stats')!;const warnings=document.querySelector('#warnings')!;let bounds=new THREE.Box3();
function frame(mode:'iso'|'top'='iso'){if(bounds.isEmpty())return;const center=bounds.getCenter(new THREE.Vector3());const size=Math.max(10,bounds.getSize(new THREE.Vector3()).length());controls.target.copy(center);camera.position.copy(center).add(mode==='top'?new THREE.Vector3(0,size,0.01):new THREE.Vector3(size*.7,size*.85,size*.7));camera.near=Math.max(.1,size/1000);camera.far=size*10;camera.updateProjectionMatrix();controls.update();}
async function load(){status.className='';status.textContent='Loading…';content.clear();overlays.clear();chunks.innerHTML='';warnings.innerHTML='';const bust=`?v=${Date.now()}`;try{const [manifest,report,gltf]=await Promise.all([fetch(`/generated/manifests/world-visual-manifest.json${bust}`).then(r=>{if(!r.ok)throw Error('Run npm run authoring:build first.');return r.json() as Promise<Manifest>}),fetch(`/generated/reports/build-report.json${bust}`).then(r=>r.json()),new GLTFLoader().loadAsync(`/generated/preview/assembled-world.glb${bust}`)]);content.add(gltf.scene);bounds.setFromObject(content);frame();for(const chunk of manifest.chunks){const object=gltf.scene.getObjectByName(`PREVIEW_${chunk.rootName}`);const label=document.createElement('label');label.innerHTML=`<input type="checkbox" checked> ${chunk.rootName}`;label.querySelector('input')!.addEventListener('change',e=>{if(object)object.visible=(e.target as HTMLInputElement).checked});chunks.append(label)}for(const guide of manifest.guides){if(guide.points.length<2)continue;const geometry=new THREE.BufferGeometry().setFromPoints(guide.points.map(p=>new THREE.Vector3(...p as [number,number,number])));const line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:guide.type==='river'?0x55ccff:0xffcc55}));overlays.add(line)}overlays.visible=false;for(const warning of report.warnings){const li=document.createElement('li');li.textContent=warning;warnings.append(li)}let triangles=0;gltf.scene.traverse(o=>{if((o as THREE.Mesh).isMesh){const g=(o as THREE.Mesh).geometry;triangles+=g.index?g.index.count/3:(g.getAttribute('position')?.count??0)/3}});stats.textContent=`${Math.round(triangles).toLocaleString()} triangles · ${renderer.info.render.calls} draw calls`;status.textContent=`Loaded ${manifest.chunks.length} chunks.`;}catch(error){status.className='error';status.textContent=error instanceof Error?error.message:String(error)}}
document.querySelector('#iso')!.addEventListener('click',()=>frame('iso'));document.querySelector('#top')!.addEventListener('click',()=>frame('top'));document.querySelector('#frame')!.addEventListener('click',()=>frame());document.querySelector('#reload')!.addEventListener('click',load);document.querySelector<HTMLInputElement>('#generated')!.addEventListener('change',e=>content.traverse(o=>{if(o.name.startsWith('GENERATED_'))o.visible=(e.target as HTMLInputElement).checked}));document.querySelector<HTMLInputElement>('#guides')!.addEventListener('change',e=>overlays.visible=(e.target as HTMLInputElement).checked);
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});void load();
